# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php

dist: trusty

matrix:
  include:
    - php: '7.1'
      env: DB=PGSQL CORE_RELEASE=3.7
    - php: '7.1'
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: '7.2'
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: '7.3'
      env: DB=MYSQL CORE_RELEASE=3.7

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit advancedworkflow/tests
