language: php

dist: xenial

services:
  - mysql
  - postgresql
  - xvfb

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_ROOT_VERSION="5.3.x-dev"

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.5.x-dev PHPUNIT_COVERAGE_TEST=1 PDO=1
    - php: 7.2
      env: DB=PGSQL RECIPE_VERSION=4.6.x-dev PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.6.x-dev PHPUNIT_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHP_UNIT_TEST=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - composer validate
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION symbiote/silverstripe-queuedjobs:^4
  # Fix for running phpunit 5 on php 7.4+
  - composer require --no-update sminnee/phpunit-mock-objects:^3
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:^2 --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ ; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
